### ISSUE TITLE
Forge couple breaks Weubui after first generation

### ISSUE THREAD

**Issue by vaskovet2** [Haoming02/sd-forge-couple#67] opened 2024-10-21 15:08 UTC
After the update today, the extension broke. It works fine for the first generation after that it gives an error
![Screenshot_1](https://github.com/user-attachments/assets/73a864ec-b508-42e2-a1b2-56ec7f69e811)
and produces a black screen it only happens after the first generation and to fix it you need to restart the WebUI for it to work again
only occurs if you Enable Forge Couple normal generation is not affected by the error is there any fix?

**Comment by Haoming02** [comment] 2024-10-21 15:11
Huh, I don't think that is caused by this Extension?

I didn't have any issues across 2 systems either. Have you tried disabling this Extension to see if the issue persists?

**Comment by vaskovet2** [comment] 2024-10-21 15:15
> Huh, I don't think that is caused by this Extension?
> 
> I didn't have any issues across 2 systems either. Have you tried disabling this Extension to see if the issue persists?

Yes I tried and there is no error I saw that Forge couple got an update but also the original Forge WebUI got an update as well this was 7-8 hours ago before that everything worked perfectly I tried going back to the previous version of WebUI but this didn't fix the issue also tried to disable and re-enable the extension and there is no change the problem only occurs when I Tick the Enable button on the Forge couple if it helps I'm using SDXL Pony didn't have any issues before today

**Comment by vaskovet2** [comment] 2024-10-21 15:25
> Sorry, I still cannot repro this...
> 
> Tested on both old Forge _(Gradio 3)_ and new Forge _(Gradio 4)_

I will try to fix it and if I do I will post in this thread if someone else has this problem

**Comment by Haoming02** [comment] 2024-10-21 15:34
Can you tell me which Sampler/Scheduler are you using?

Cause the error seems to be caused by the Sampler

**Comment by vaskovet2** [comment] 2024-10-21 15:40
> Can you tell me which Sampler/Scheduler are you using?
> 
> Cause the error seems to be caused by the Sampler

I use Sampler Euler A and leave the scheduler on Automatic

**Comment by vaskovet2** [comment] 2024-10-21 16:15
> I'm also using `Euler a` with `Automatic`...
> 
> Welp, I'm out of idea then

A fresh installation of WebUI fixes the problem. I am still not sure what caused it in the first place I'm now slowly installing and testing all extensions that I previously had to see if something breaks again

**Comment by vaskovet2** [comment] 2024-10-21 16:34
> > I'm also using `Euler a` with `Automatic`...
> > Welp, I'm out of idea then
> 
> A fresh installation of WebUI fixes the problem. I am still not sure what caused it in the first place I'm now slowly installing and testing all extensions that I previously had to see if something breaks again

Everything works fine for now I installed every extension that I had previously and there are no errors

**Comment by Haoming02** [comment] 2024-10-21 16:35
... 

How XD

**Comment by vaskovet2** [comment] 2024-10-21 16:42
> ...
> 
> How XD

Yeah that's what I'm asking myself as well I just deleted every instance of ForgeUI installed it again on the Newest version and it just worked I can't explain it to me either

The closest thing that I can think of is that I made some changes in the Settings of the Optimizers and Samplers but that was like 3 months ago not sure if it's this but a clean install reset everything to default

**Comment by Haoming02** [comment] 2024-10-22 00:31
Well, glad that it's working now.

I'mma close this then.

**Closed by Haoming02** 2024-10-22 00:31 UTC

**Comment by vaskovet2** [comment] 2024-10-25 13:09
Found out what causes the problem if you use HighRes fix + Forge couple it breaks the generation after the first one the problem appeared once again and I did some testing, but I'm not sure if the high res is the problem or the model I'm using currently using 4x_foolhardy_Remacri for a while will change the model to see if this fixes the issue
