### ISSUE TITLE
- ERROR - Not Enough Lines in Prompt... [1 / 2]

### ISSUE THREAD

**Issue by medoro** [Haoming02/sd-forge-couple#80] opened 2024-12-07 18:08 UTC
I have this error and the prompt is:

Scene with 2 girls
a girl sitting cross-legged on the floor, young, looks up looking at another, short hair, light-colored, wearing a loose, comfortable sweater and joggers, smile,
a girl  mischievous-looking, young, descending a staircase, playful, sly, cheeky, flowing dark hair, fitted top, casual jeans, her pose dynamic she holds the stair railing

I also tried cut&paste of example prompt from here and it works, I changed with mine except last word of each line and it gives me an error

version: [f2.0.1v1.10.1-previous-630-g85a7db3c](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/85a7db3c0f076d186e630763139d082d31609dc0)  •  python: 3.10.6  •  torch: 2.3.1+cu121  •  xformers: N/A  •  gradio: 4.40.0  •  checkpoint: [4b5f77a9eb](https://google.com/search?q=4b5f77a9eb56e3a66b529235d49927d764eba0a4f8a76c86afd06c260e750c96)

**Comment by Haoming02** [comment] 2024-12-07 18:10
Did you change the `Couple Separator`?

**Comment by medoro** [comment] 2024-12-07 20:09
i tried typing \n bby hand and | is there another character I can try?

**Comment by Haoming02** [comment] 2024-12-07 20:53
You can just leave it empty

**Comment by Haoming02** [comment] 2024-12-10 06:24
Hello, does the problem still persist?

**Comment by Andrey36652** [comment] 2024-12-10 08:16
I think I have similar problem. forge couple v3.3.4 on reforge f1.4.0dev-v1.10.1RC-latest-1453-g854af280
3 lines in pos prompt, 1 line in neg. 
![image](https://github.com/user-attachments/assets/44d29343-00b2-4e12-9818-1747b45692dc)
Each time I press "Generate" button I see an error in python console
```
[ForgeCouple] - ERROR - Not Enough Lines in Prompt... [1 / 3]
```

**Comment by Haoming02** [comment] 2024-12-10 08:24
Sorry, still can't reproduce this.

Can you incldue a screenshot of your prompts?

**Comment by Andrey36652** [comment] 2024-12-10 08:29
resolved it. "Dynamic prompts" builtin extension by default removes all '\n' from prompt, it's possible to adjust this behaviour in settings. 
![image](https://github.com/user-attachments/assets/5eae6884-c9a7-40c5-976c-0f79b136aa0c)
![image](https://github.com/user-attachments/assets/9523836b-75a8-4afc-869f-53351abd0048)
btw in Advanced mode should all weights of regions sums up to 1.0?

**Comment by Haoming02** [comment] 2024-12-10 08:31
> btw in Advanced mode should all weights of regions sums up to 1.0?

Nope, the only requirement is that the whole image must contain weight.

**Comment by Andrey36652** [comment] 2024-12-10 08:35
Is these weights added? Does this have equivalent effect as CFG increasing or tags weights increasing?

**Comment by Haoming02** [comment] 2024-12-10 08:38
Hmm, probably closer to prompt emphasis *(**ie.** `(` `)` feature)*.

I tried setting really high weights for a layer before, but it didn't "burn" the image like high `CFG` would do.

**Comment by Haoming02** [comment] 2024-12-12 06:21
@medoro Do you perhaps have the `Dynamic Prompts` Extension as well?

**Comment by Haoming02** [comment] 2024-12-16 01:35
I'm closing this, assuming it's the same cause then *(**ie.** 3rd-party Extension)*

**Closed by Haoming02** 2024-12-16 01:35 UTC
